Ext.define('Senchaslide.view.Asociaciones', {
    extend: 'Ext.Panel',   
    id: 'viewAsociaciones',
    
    config: {
        cls: 'asociaciones',        
        scrollable: true,
        html: [
            '<div>', 
            '<p>Los modelos pueden ser enlazados entre ellos con la API de asociaciones. Muchas aplicaciones tratan con muy variados modelos, y los modelos ',
            'siempre están relacionados entre sí. Estas relaciones pueden expresarse de la siguiente forma: ',                       
            '<pre class="prettyprint lang-javascript">',
            'Ext.define(\'User\', {<br />',
            '   extend: \'Ext.data.Model\',<br />',
            '   fields: [\'id\', \'name\', \'age\', \'gender\'],<br />',
            '   proxy: {<br />',
            '       type: \'rest\',<br />',
            '       url: \'data/users\',<br />',
            '       reader: {<br />',
            '           type: \'json\',<br />',
            '           root: \'users\'<br />',
            '       }<br />',
            '   },<br />',
            '<br />',
            '   hasMany: \'Post\' // shorthand de { model: \'Post\', name: \'post\' }<br />',
            '});<br />',
            '<br />',            
            'Ext.define(\'Post\', {<br />',
            '   extend: \'Ext.data.Model\',<br />',
            '   fields: [\'id\', \'user_id\', \'title\', \'body\'],<br />',
            '<br />',
            '   proxy: {<br />',
            '       type: \'rest\',<br />',
            '       url: \'data/posts\',<br />',
            '       reader: {<br />',
            '           type: \'json\',<br />',
            '           root: \'post\'<br />',
            '       }<br />',
            '   },<br />',
            '   belongsTo: \'User\',<br />',
            '   hasMany: {model: \'Comment\', name: \'comments\'}<br />',
            '});<br />',
            '<br />',
            'Ext.define(\'Comment\', {<br />',
            '   extend: \'Ext.data.Model\',<br />',
            '   fields: [\'id\', \'post_id\', \'name\', \'message\'],<br />',
            '<br />',
            '   belongsTo: \'Post\'<br />',
            '});',
            '</pre></p>',         
            '</div>'
        ].join("")
    }
});