Ext.define('Senchaslide.view.HelloWorld', {
    extend: 'Ext.Panel',
    id: 'viewHelloWorld',
    
    config: {
        cls: 'helloworld',
        scrollable: true,
        html: [
            '<div class="main">',
            '<p>Creamos un nuevo directorio que sirva como raíz de la aplicación llamado <code>helloworld</code>.<br /> ',
            'Creamos un enlace simbólico o copiamos el directorio del SDK en <code>lib/touch</code> y creamos el archivo <code>index.html</code>:</p>',            
            '<p><pre class="prettyprint">',
            '&lt;!DOCTYPE html><br />',
            '&lt;html><br />',
            '    &lt;head><br />',
            '        &lt;title>Hello World!</title>                    <br />',
            '        &lt;script src="lib/touch/sencha-touch.js" type="text/javascript">&lt;/script><br />',
            '        &lt;link rel="stylesheet" href="lib/touch/resources/css/sencha-touch.css" type="text/css"><br />',
            '        <br />',
            '        &lt;script type="text/javascript"><br />',
            '            new Ext.application({<br />',
            '                name: "Hello World",<br />',
            '                <br />',
            '                launch: function() {<br />',
            '                    Ext.create("Ext.TabPanel", {<br />',
            '                        fullscreen: true,<br />',
            '                        dockedItems: [{<br />',
            '                            dock: "bottom",<br />',
            '                            xtype: "toolbar",<br />',
            '                            title: "Hello World!"<br />',
            '                        }],<br />',
            '                        items: [{<br />',
            '                            title: "Hello",<br />',
            '                            html: "This is a Hello"<br />',
            '                        }, {<br />',
            '                            title: "World",<br />',
            '                            html: "World application"<br />',
            '                        }],<br /><br />',
            '                        styleHtmlContent: true<br />',
            '                    });<br />',
            '                }<br />',
            '            });<br />',
            '        &lt;/script><br />',
            '        <br />',
            '    &lt;/head><br />',
            '    &lt;body>&lt;/body><br />',
            '&lt;/html><br />',            
            '</pre></p>',            
            '</div>'
        ].join("")
    }
});